/*Auto generated by Angular Framework - Tuned by Demitri Bannoura*/
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-banner',
  templateUrl: './banner.component.html',
  styleUrls: ['./banner.component.css']
})
export class BannerComponent implements OnInit {

  constructor() { }

  public isMenuCollapsed = true;

  ngOnInit(): void {
  }

}
