/*Auto generated by Angular Framework - Tuned by Demitri Bannoura*/
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-banner',
  templateUrl: './banner.component.html',
  styleUrls: ['./banner.component.css'],
})
export class BannerComponent implements OnInit {
  constructor(private AuthReRoute: Router) {}

  public isMenuCollapsed = true;

  ngOnInit(): void {}

  logoclick() {
    var currentUser = JSON.parse(localStorage.getItem('currentUser') as string);
    if (currentUser != undefined) {
      this.AuthReRoute.navigate(['/home']);
    } else {
      this.AuthReRoute.navigate(['/login']);
    }
  }
}
