import { Component } from '@angular/core';
import { CalendarView } from 'angular-calendar';
import { CalendarEvent } from 'angular-calendar';
import { startOfDay } from 'date-fns';

//Auto generated by angular
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
//Class by Sahil Pyakurel 
export class AppComponent {
  
  title = 'Tightrope';
  


}

