import { Component,HostListener } from '@angular/core';
import { CalendarView } from 'angular-calendar';
import { CalendarEvent } from 'angular-calendar';
import { startOfDay } from 'date-fns';
import { AuthService } from './service/auth.service';
import { PublicService } from './service/public.service';

//Auto generated by angular
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
//Class by Sahil Pyakurel 
export class AppComponent {
  
  title = 'Tightrope';
  
  msg: any;
  constructor(private pService: PublicService) { }

  ngOnInit(): void {
    this.showMessage()
  }

  showMessage(){
    this.pService.getMessage().subscribe(data => {this.msg = data,console.log(this.msg)});
  }

}


